Задача 0

In [ ]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser = pd.Series(mydict)
print (ser.head())

a    0
b    1
c    2
e    3
d    4
dtype: int64


Задача 1

In [ ]:
df = ser.to_frame().reset_index()
print (df.head())

  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


Задача 2

In [ ]:
import numpy as np
import pandas as pd
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
Ser1 = pd.Series(mylist)
Ser2 = pd.Series(myarr)
df1 = pd.DataFrame(Ser1, columns= ['1'])
df2 = pd.DataFrame(Ser2, columns= ['2'])
dataframe = pd.concat([df1, df2], axis=1)
print (dataframe.head())

   1  2
0  a  0
1  b  1
2  c  2
3  e  3
4  d  4


Задача 3

In [ ]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
df= pd.DataFrame(ser, columns = ['latin_letters'] )
print (df.head())

  latin_letters
0             a
1             b
2             c
3             e
4             d


Задача 4

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

res = ser1[~np.isin(ser1, ser2)]
print(res)

0    1
1    2
2    3
dtype: int64


Задача 5

In [ ]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

union = pd.Series(np.union1d(ser1, ser2))
intersect = pd.Series(np.intersect1d(ser1, ser2))
notcommonseries = union[~union.isin(intersect)]
print(notcommonseries)

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64


Задача 6

In [ ]:
ser = pd.Series(np.random.normal(10, 5, 25))

result = np.percentile(ser, q=[0, 25, 50, 75, 100])
print("\nMinimum, 25th percentile, median, 75th, and maximum of a given series:")
print(result)


Minimum, 25th percentile, median, 75th, and maximum of a given series:
[-1.76485925  4.88282134  8.68076882 12.08738767 14.59660767]


Задача 7

In [ ]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

print(ser.value_counts())

g    5
b    5
c    4
h    4
f    3
a    3
e    3
d    3
dtype: int64


Задача 8

In [ ]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

print("Топ 2:", ser.value_counts())
ser[~ser.isin(ser.value_counts().index[:2])] = "Прочее"
print("\n")
print(ser)

Топ 2: 2    6
3    3
4    2
1    1
dtype: int64


0          2
1     Прочее
2          2
3          2
4          3
5     Прочее
6          3
7          2
8          2
9          3
10    Прочее
11         2
dtype: object


Задача 9

In [ ]:
ser = pd.Series(np.random.random(20))

print(ser.head())
print("\n")
pd.qcut(ser,q=[0,.10,.20,.30,.40,.50,.60,.70,.80,.90,1],labels=['1','2','3','4','5','6','7','8','9','10']).head()


0    0.592746
1    0.034493
2    0.903521
3    0.607705
4    0.497667
dtype: float64




0     6
1     1
2    10
3     6
4     5
dtype: category
Categories (10, object): ['1' < '2' < '3' < '4' ... '7' < '8' < '9' < '10']

Задача 10

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 35))

df=pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  7  9  6  7  1
1  6  1  2  3  7
2  9  8  7  1  3
3  4  7  6  8  9
4  1  9  9  6  3
5  6  3  7  7  3
6  2  7  5  5  8


Задача 11

In [ ]:
ser = pd.Series(np.random.randint(1, 10, 7))

res= ser[ser % 3 == 0].index
print(res)

Int64Index([0, 1, 3], dtype='int64')


Задача 12

In [ ]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

res = ser.take(pos)
print(res)


0     a
4     e
8     i
14    o
20    u
dtype: object


Задача 13

In [ ]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

res_vertical = ser1.append(ser2)
res_horizontal = pd.concat([ser1, ser2], axis=1)

print(res_vertical)
print("\n")
print(res_horizontal)

0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


<ipython-input-15-6c95b54278af>:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  res_vertical = ser1.append(ser2)


Задача 14

In [ ]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

[np.where(i==ser1)[0].tolist()[0] for i in ser2]
[pd.Index(ser1).get_loc(i) for i in ser2]

[5, 4, 0, 8]

Задача 15

In [ ]:

truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth-pred)**2)

0.31981781897935535

Задача 16

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

newser=ser.map(lambda x: x.title())
print(newser)

0     How
1      To
2    Kick
3    Ass?
dtype: object


Задача 17

In [ ]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

res = ser.map(lambda calc: len(calc))
print(res)

0    3
1    2
2    4
3    4
dtype: int64


Задача 18

In [ ]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff())

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64


Задача 19

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

res = pd.to_datetime(ser)
print(res)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


Задача 20

In [ ]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

from dateutil.parser import parse
res = ser.map(lambda x: parse(x))
print("Day of month:")
print(res.dt.day.tolist())
print("Day of year:")
print(res.dt.dayofyear.tolist())
print("Week number:")
print(res.dt.weekofyear.tolist())
print("Day of week:")
print(list(res.dt.day_name()))

Day of month:
[1, 2, 3, 4, 5, 6]
Day of year:
[1, 33, 63, 94, 125, 157]
Week number:
[53, 5, 9, 14, 19, 23]
Day of week:
['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


<ipython-input-22-d2f430d34987>:10: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  print(res.dt.weekofyear.tolist())


Задача 21

In [ ]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

print(pd.to_datetime(ser).apply(lambda x: x.replace(day=4)))

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


Задача 22

In [ ]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter

mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiouаоиеёэыуюя')]) >= 2)
res = ser[mask]
print(res)

0     Apple
1    Orange
4     Money
dtype: object


Задача 23

In [ ]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'

import re
mask = emails.map(lambda x: bool(re.match(pattern, x)))
res = emails[mask]
print(res)

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


Задача 24

In [ ]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weights.tolist())
print(fruit.tolist())
print("\n")

weights.groupby(fruit).mean()

[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
['banana', 'banana', 'banana', 'apple', 'carrot', 'apple', 'apple', 'carrot', 'apple', 'apple']




apple     7.2
banana    2.0
carrot    6.5
dtype: float64

Задача 25

In [ ]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

res = sum((p-q)**2)**0.5
print(res)

18.16590212458495


Задача 26

In [ ]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs

array([1, 5, 7])

Задача 27

In [ ]:
my_str = 'dbc deb abed gade'

ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
least_freq = freq.dropna().index[-1]
''.join(ser.replace(' ', least_freq))

'dbcgdebgabedggade'

Задача 28

In [ ]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser

2000-01-01    2
2000-01-08    2
2000-01-15    4
2000-01-22    1
2000-01-29    4
2000-02-05    1
2000-02-12    8
2000-02-19    8
2000-02-26    1
2000-03-04    7
Freq: W-SAT, dtype: int64

Задача 29

In [ ]:
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)

print("\n")
ser=ser.resample('D').ffill()  # fill with previous value
ser=ser.resample('D').bfill()  # fill with previous value
print(ser)

2000-01-01     1.0
2000-01-03    10.0
2000-01-06     3.0
2000-01-08     NaN
dtype: float64


2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
Freq: D, dtype: float64


Задача 30

In [ ]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorr = [ser.autocorr(lag=i).round(2) for i in range(20)]
print(autocorr)
print('Наиб. корреляция: ', np.argmax(np.abs(autocorr[1:]))+1)

[1.0, -0.12, -0.05, -0.1, -0.25, 0.34, -0.13, 0.46, 0.04, -0.55, 0.15, -0.03, 0.35, 0.21, 0.01, -0.27, -0.27, -0.92, 1.0, nan]
Наиб. корреляция:  19


/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2845: RuntimeWarning: Degrees of freedom <= 0 for slice
  c = cov(x, y, rowvar, dtype=dtype)
/usr/local/lib/python3.10/dist-packages/numpy/lib/function_base.py:2704: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)


Задача 31

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
df2 = pd.concat([chunk.iloc[0] for chunk in df], axis=1)
df2 = df2.transpose()
print(df2.head())


        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  


Задача 32

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', converters={'medv': lambda x: 'High' if float(x) > 25 else 'Low'})
print(df.head())

      crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98   Low  
1  396.90   9.14   Low  
2  392.83   4.03  High  
3  394.63   2.94  High  
4  396.90   5.33  High  


Задача 33

In [ ]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)

array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])

Задача 34

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


Задача 35

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.shape)
print(df.dtypes)
print(df.dtypes.value_counts())
df_stats = df.describe()
df_arr = df.values
df_list = df.values.tolist()

(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object
float64    18
object      9
dtype: int64


Задача 36

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.loc[df.Price == np.max(df.Price), ['Manufacturer', 'Model', 'Type']])
row, col = np.where(df.values == np.max(df.Price))
print(df.iat[row[0], col[0]])
print(df.iloc[row[0], col[0]])

     Manufacturer Model     Type
58  Mercedes-Benz  300E  Midsize
61.9
61.9


Задача 37

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)

df=df.rename(columns = {'Type':'CarType'})
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
       'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
       'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
       'Make'],
      dtype='object')
Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


Задача 38

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.isnull().values.any()

True

Задача 39

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missings_each_col = df.apply(lambda x: x.isnull().sum())
print(n_missings_each_col.argmax())
print(df.apply(lambda x: x.isnull().sum()).idxmax())

23
Luggage.room


Задача 40

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


Задача 41

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

d = {'Min.Price': np.nanmean, 'Max.Price': np.nanmedian}
df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x, d: x.fillna(d[x.name](x)), args=(d, ))
print(df_out.head())

   Min.Price  Max.Price
0  12.900000      18.80
1  29.200000      38.70
2  25.900000      32.30
3  17.118605      44.60
4  17.118605      19.15


Задача 42

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

pandas.core.frame.DataFrame

Задача 43

In [ ]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

df[list('cbade')]
def switch_columns(df, col1=None, col2=None):
    colnames = df.columns.tolist()
    i1, i2 = colnames.index(col1), colnames.index(col2)
    colnames[i2], colnames[i1] = colnames[i1], colnames[i2]
    return df[colnames]
df1 = switch_columns(df, 'a', 'c')
df[sorted(df.columns)]

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

Задача 44

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

Задача 45

In [ ]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])

df.round(4)
df.apply(lambda x: '%.4f' % x, axis=1)
pd.set_option('display.float_format', lambda x: '%.4f' % x)
pd.options.display.float_format = '{:.4f}'.format
print(df)
pd.options.display.float_format = None

   random
0  0.0000
1  0.5238
2  0.0252
3  0.1389


Задача 46

In [ ]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({'random': '{0:.2%}'.format,})
out

Задача 47

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Задача 48

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df_out=df[['Manufacturer', 'Model', 'Type', 'Min.Price', 'Max.Price']] = df[['Manufacturer', 'Model', 'Type', 'Min.Price', 'Max.Price']].fillna('missing')
print(df_out.head())
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

  Manufacturer    Model     Type Min.Price Max.Price
0        Acura  Integra    Small      12.9      18.8
1      missing   Legend  Midsize      29.2      38.7
2         Audi       90  Compact      25.9      32.3
3         Audi      100  Midsize   missing      44.6
4          BMW     535i  Midsize   missing   missing
True


Задача 49

In [ ]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))

print(df)
print("\n")
print(df['a'].argsort())
n = 5
print("\n")
df['a'].argsort()[::-1][n]

    a   b   c
0  22  12   2
1  22  20  29
2  15  25   6
3   6   6  13
4   9  23  14
5  20  21  19
6  18  16  17
7   2  17  22
8  17   5  21
9  20   6  12


0    7
1    3
2    4
3    2
4    8
5    6
6    5
7    9
8    0
9    1
Name: a, dtype: int64




6

Задача 50

In [ ]:
ser = pd.Series(np.random.randint(1, 100, 15))

print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
ser_mean = np.mean(ser.values).round()
greater_than_mean_arr = ser.where(ser > ser_mean).dropna().sort_values()
row_second_largest_num = greater_than_mean_arr.index[1]
row_second_largest_num

ser:  [82, 87, 49, 72, 85, 72, 15, 37, 8, 54, 74, 92, 5, 40, 64] mean:  56


3

Задача 51

In [ ]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rowsums = df.apply(np.sum, axis=1).sort_values()
print(rowsums)
last_two_rows = df.iloc[np.where(rowsums > 100)[0][-2:], :]
print(last_two_rows)


3      81
9      83
10     85
6      86
12     86
     ... 
1     104
14    108
7     112
4     126
13    130
Length: 15, dtype: int64
     0   1   2   3
13  31  33  39  27
14  37  11  30  30


Задача 52

In [ ]:
ser = pd.Series(np.logspace(-2, 2, 30))

print(ser)
print("\n")
low_perc = ser.quantile(q=0.05)
print(low_perc)
high_perc = ser.quantile(q=0.95)
print(high_perc)
ser.where(ser > low_perc, other=low_perc, inplace=True)
ser.where(ser < high_perc, other=high_perc, inplace=True)
print("\n")
print(ser)

0       0.010000
1       0.013738
2       0.018874
3       0.025929
4       0.035622
         ...    
25     28.072162
26     38.566204
27     52.983169
28     72.789538
29    100.000000
Length: 30, dtype: float64


0.016049294076965887
63.87667222018393


0      0.016049
1      0.016049
2      0.018874
3      0.025929
4      0.035622
        ...    
25    28.072162
26    38.566204
27    52.983169
28    63.876672
29    63.876672
Length: 30, dtype: float64


Задача 53

In [ ]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))

print(df)
print("\n")
arr = df[df > 0].values.flatten()
pos_arr = arr[~np.isnan(arr)]
n = int(np.floor(pos_arr.shape[0]**.5))
top_indexes = np.argsort(pos_arr)[::-1]
output = np.take(pos_arr, sorted(top_indexes[:n**2])).reshape(n, -1)
print(output)

    0   1   2   3   4   5   6   7   8   9
0   9 -12  32  48  15  22  37  24  29 -13
1  19  33  -1  -4 -10 -20  45  19   4  33
2  46  40  46  39  -4  45 -14  46  17  15
3  44  35  15  30  17   0 -18   2   4   9
4  33 -15  41  10 -16  45  23  48  13  31
5  23   7 -11 -11  -4  43   1 -13  27  18
6   4  14  -7  16  33  -6  34 -20  42  12
7   4  10  33  20  16  29   1  26  10 -13
8  39   8   3  34  44  12  12  15  14   7
9  42  39  35  28  39  42  28  22 -14  24


[[32. 48. 15. 22. 37. 24. 29. 19.]
 [33. 45. 19. 33. 46. 40. 46. 39.]
 [45. 46. 17. 15. 44. 35. 15. 30.]
 [17. 33. 41. 45. 23. 48. 13. 31.]
 [23. 43. 27. 18. 14. 16. 33. 34.]
 [42. 12. 33. 20. 16. 29. 26. 10.]
 [39. 34. 44. 12. 12. 15. 14. 42.]
 [39. 35. 28. 39. 42. 28. 22. 24.]]


Задача 54

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print("\n")
def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df
print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


Задача 55

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

print(df)
print("\n")
df.iloc[::-1]

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24




0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4

Задача 56

In [ ]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

print(df)
print("\n")
one_hot = pd.get_dummies(df["a"])
print(one_hot)
print("\n")
pd.concat([one_hot, df[["b","c","d","e"]]],axis=1)

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24


   0   5   10  15  20
0   1   0   0   0   0
1   0   1   0   0   0
2   0   0   1   0   0
3   0   0   0   1   0
4   0   0   0   0   1




0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24

Задача 57

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

print(df)
print("\n")
row_high_num = df.sum(axis=0).argmax()
print(row_high_num)

    0   1   2   3
0  37  81  20  64
1  17  82  18  20
2  56  94  42  99
3  22  53  27  70
4  82  43  99  75
5  81  84  99  40
6  31  57  27   5
7  41  71   2  20
8   1  13  87  59
9  25  76  48  59


1


Задача 58

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))

print(df)
print("\n")
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(df)
distances, indices = nbrs.kneighbors(df)
df.insert(4,"nearest row",df.index[indices[:,1]],True)
df.insert(5,"distances", distances[:,1],True)
print(df.index[indices[:,1]])

    p   q   r   s
a  59  81  53  42
b  71  99  41  65
c   5  45  50  54
d  82  62  33  87
e  61  29  96  26
f  65  81  72  97
g  59  43  65  52
h  47  76  93   9
i  29  53  79  85
j  44   2  88  61


Index(['b', 'a', 'i', 'b', 'g', 'd', 'a', 'e', 'f', 'e'], dtype='object')


Задача 59

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))

print(df)
print("\n")
abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Макс. корреляция каждого столбца: ', np.round(max_corr.tolist(), 2))

    p   q   r   s   t   u   v   w   x   y
a  46  42  72  66  56  41  35  42   1  75
b  83  43  66  67  82   2  28   7  22  87
c  73  20  97  35  91  31  93  45  50  82
d  61  25  45  58  44  92  70  74  95   3
e  62  38  80   7  56  16  44  87  29  39
f  61  11  70  81  95   8  23  45  89  70
g  69  65  58  28  90  56  37  92  77  48
h  35  69  52  87  38   9  56  44  43  38


Макс. корреляция каждого столбца:  [0.7  0.44 0.66 0.66 0.7  0.63 0.39 0.67 0.5  0.67]


Задача 60

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
min_by_max = df.apply(lambda x: np.min(x)/np.max(x), axis=1)
print(min_by_max)

    0   1   2   3   4   5   6   7   8   9
0  27  76  75  56   5  81  39   9  53  78
1  10  98  82   6  48  49  57  10  42  22
2  62  19  73   8  79  13  79   7  59  77
3  40  16   5  70  70  21  97  83  38  39
4  84  68  33   2  99  33  11  79  44  25
5  77  87  71  48  57  76  12   2  35  36
6   4  90  44  55  21  93  76  10  98   4
7  92   7   8  38  57  72  23  86  71  71


0    0.061728
1    0.061224
2    0.088608
3    0.051546
4    0.020202
5    0.022989
6    0.040816
7    0.076087
dtype: float64


Задача 61

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)

    0   1   2   3   4   5   6   7   8   9
0  95  93  20  89  34  69  35  62  79  11
1  11  74  38  33  12  71  79  81  41  11
2  14  80  89  89  81  14  48  25  36  25
3  82  18  10  20  50  50  15  50  96   8
4  60   3  61  48  70  75  62  89  89  61
5  24  12  92  82  94  51  90  45  20  98
6   4  44  16  32  32  70  84  35  83  29
7  10  55  70  59  40  10  59  30  43  74


    0   1   2   3   4  ...   6   7   8   9  penultimate
0  95  93  20  89  34  ...  35  62  79  11           93
1  11  74  38  33  12  ...  79  81  41  11           79
2  14  80  89  89  81  ...  48  25  36  25           81
3  82  18  10  20  50  ...  15  50  96   8           82
4  60   3  61  48  70  ...  62  89  89  61           75
5  24  12  92  82  94  ...  90  45  20  98           94
6   4  44  16  32  32  ...  84  35  83  29           83
7  10  55  70  59  40  ...  59  30  43  74           70

[8 rows x 11 columns]


Задача 62

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('№1\n',out1)
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('№2\n', out2)

    0   1   2   3   4   5   6   7   8   9
0  83  53  79  26  58  69  34   5  57  58
1  78  97  42  32  13  38  95  31  58   8
2  35  43  79  87  38  64  87  47  52  49
3  79   5  94  40  88  70  84  23  60  92
4  58   5  51  74  37  68  27  56  42  22
5  72  37  42  89  24  28  18  33  61  85
6  53  70  70  60  15  78  64  51  33  18
7  66  72  14  66  31  86  28  48  72  50


№1
       0     1     2     3     4     5     6     7     8     9
0  1.08  0.16  0.77 -1.37  0.81  0.32 -0.66 -1.86  0.22  0.33
1  0.77  1.52 -0.64 -1.12 -1.01 -1.25  1.29 -0.34  0.30 -1.30
2 -1.89 -0.15  0.77  1.14  0.00  0.07  1.03  0.60 -0.20  0.04
3  0.83 -1.32  1.34 -0.79  2.02  0.37  0.94 -0.80  0.47  1.44
4 -0.46 -1.32 -0.30  0.61 -0.04  0.27 -0.88  1.13 -1.02 -0.84
5  0.40 -0.33 -0.64  1.22 -0.56 -1.76 -1.17 -0.22  0.55  1.21
6 -0.77  0.69  0.42  0.03 -0.93  0.78  0.30  0.83 -1.77 -0.97
7  0.03  0.75 -1.71  0.28 -0.28  1.19 -0.85  0.66  1.46  0.07
№2
       0     1     2     3     4     5     6     7     

Задача 63

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

print(df)
print("\n")
print([df.iloc[i].corr(df.iloc[i+1]).round(2) for i in range(df.shape[0])[:-1]])

    0   1   2   3   4   5   6   7   8   9
0  22  50  20  86   4  78  74  33  41  81
1  32  26  83  43  34  30  22  24  70  48
2  50  32  24   9  41   9  31  60  51  94
3  33   5  84  27  56  72  71  83  23   1
4  70  53  51  44   2  46  97  52  43   6
5  39  93   1  60  63  53   4  49  26  57
6  50  92  78  89  40  73  77  53  30  54
7  66  63  23  45  50  19  20  39  69  42


[-0.21, 0.03, -0.38, 0.33, -0.48, 0.15, -0.42]


Задача 64

In [ ]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))

print(df)
print("\n")
for i in range(df.shape[0]):
    df.iat[i, i] = 0
    df.iat[df.shape[0]-i-1, i] = 0
print(df)

    0   1   2   3   4   5   6   7   8   9
0  31  62  27  47  25  14  26  26   1  55
1  54   2  75  86  48  22  10   7  83  48
2  22   7  33  89  80  28  71  59  49  33
3  17  37  29  80  76  43  18  55  55  22
4  92  10  62  19  94  25  30  33  97   6
5  51  21  51  41  95  72  91  68  59  17
6  34  91  80  79   5  38  60  76  75  97
7  57  59  79  87  12  93  36  69  54  73
8  40  96   9  87   2  30  59  46  28  85
9  65  85  89  49  62  70  97   5  80   5


    0   1   2   3   4   5   6   7   8   9
0   0  62  27  47  25  14  26  26   1   0
1  54   0  75  86  48  22  10   7   0  48
2  22   7   0  89  80  28  71   0  49  33
3  17  37  29   0  76  43   0  55  55  22
4  92  10  62  19   0   0  30  33  97   6
5  51  21  51  41   0   0  91  68  59  17
6  34  91  80   0   5  38   0  76  75  97
7  57  59   0  87  12  93  36   0  54  73
8  40   0   9  87   2  30  59  46   0  85
9   0  85  89  49  62  70  97   5  80   0


Задача 65

In [ ]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

print(df)
print("\n")
df_grouped = df.groupby(['col1'])
df_grouped.get_group('apple')
for i, dff in df_grouped:
    if i == 'apple':
        print(dff)


     col1      col2  col3
0   apple  0.527159     6
1  banana  0.942934     5
2  orange  0.723250    10
3   apple  0.553954    12
4  banana  0.563323    11
5  orange  0.925764    11
6   apple  0.037012    11
7  banana  0.511491    13
8  orange  0.694102    12


    col1      col2  col3
0  apple  0.527159     6
3  apple  0.553954    12
6  apple  0.037012    11


<ipython-input-67-8b40a11c707d>:9: FutureWarning: In a future version of pandas, a length 1 tuple will be returned when iterating over a groupby with a grouper equal to a list of length 1. Don't supply a list with a single grouper to avoid this warning.
  for i, dff in df_grouped:


Задача 66

In [ ]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)
print("\n")
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]

    fruit     taste  price
0   apple  0.526519      7
1  banana  0.010378      5
2  orange  0.786067      9
3   apple  0.130704     10
4  banana  0.484881      5
5  orange  0.539761      9
6   apple  0.370781      1
7  banana  0.514121      3
8  orange  0.121514     13




0.48488063730888376

Задача 67

In [ ]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)
print("\n")
out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)

    fruit    rating  price
0   apple  0.062974     13
1  banana  0.122478     13
2  orange  0.136631      6
3   apple  0.187832     14
4  banana  0.121842      9
5  orange  0.452950      4
6   apple  0.659701     14
7  banana  0.866376      3
8  orange  0.536028     14


    fruit      price
0   apple  13.666667
1  banana   8.333333
2  orange   8.000000


Задача 68

In [ ]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

print(df1)
print("\n")
print(df2)
print("\n")
pd.merge(df1, df2, how='inner', left_on=['fruit', 'weight'], right_on=['pazham', 'kilo'], suffixes=['_left', '_right'])

    fruit  weight  price
0   apple    high      0
1  banana  medium      6
2  orange     low      4
3   apple    high      7
4  banana  medium      4
5  orange     low     14
6   apple    high      4
7  banana  medium      9
8  orange     low      1


   pazham  kilo  price
0   apple  high      4
1  orange   low      9
2    pine  high      9
3   apple   low      0
4  orange  high      0
5    pine   low     10




fruit weight  price_left  pazham  kilo  price_right
0   apple   high           0   apple  high            4
1   apple   high           7   apple  high            4
2   apple   high           4   apple  high            4
3  orange    low           4  orange   low            9
4  orange    low          14  orange   low            9
5  orange    low           1  orange   low            9

Задача 69

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

print(df)
print("\n")
df['a_lag1'] = df['a'].shift(-1)
df['b_lead1'] = df['b'].shift(1)
print(df)

    a   b   c   d
0  72  89  44  37
1  96  76  61  96
2  26  22  88  82
3  20  77  28  76
4  43  19  53  49


    a   b   c   d  a_lag1  b_lead1
0  72  89  44  37    96.0      NaN
1  96  76  61  96    26.0     89.0
2  26  22  88  82    20.0     76.0
3  20  77  28  76    43.0     22.0
4  43  19  53  49     NaN     77.0


Задача 71

In [ ]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))

print(df)
print("\n")
pd.value_counts(df.values.ravel())

   a  b  c  d
0  2  5  5  2
1  4  3  6  2
2  6  7  2  6
3  1  7  6  4
4  3  3  6  9




6    5
2    4
3    3
5    2
4    2
7    2
1    1
9    1
dtype: int64

Задача 72

In [ ]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
print("\n")
df_out = df.row.str.split(',|\t', expand=True)
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

                          row
0          STD, City    State
1  33, Kolkata    West Bengal
2   44, Chennai    Tamil Nadu
3  40, Hyderabad    Telengana
4  80, Bangalore    Karnataka


0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
